main:
  - name: Home
    url: /en/
    weight: 10

  - name: Research
    url: /research/
    weight: 20

  - name: News
    url: /en/post/
    weight: 30

  - name: Publications
    url: /en/publication/
    weight: 40

  - name: People
    url: /en/people/
    weight: 50

  - name: Join Us
    url: /en/join/
    weight: 60

  - name: Contact
    url: /en/contact/
    weight: 70

   
