main:
  - name: 首页
    url: /
    weight: 10

  - name: 实验室介绍
    url: /research/
    weight: 20

  - name: 新闻
    url: /post/
    weight: 30

  - name: 论文
    url: /publication/
    weight: 40

  - name: 成员
    url: /people/
    weight: 50

  - name: 加入我们
    url: /join/
    weight: 60

  - name: 联系方式
    url: /contact/
    weight: 70
